owner: tinyweatherforecastgermanygroup
repo: statuspage

sites:
  - name: Codeberg
    url: https://codeberg.org
  - name: DWD Open Data Server
    url: https://opendata.dwd.de
  - name: DWD Geoserver
    url: https://maps.dwd.de

status-website:
  baseUrl: /statuspage
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TinyWeatherForecastGermany
  introTitle: "TinyWeatherForecastGermany is an open source weather app for android devices."
  introMessage: Lorem Ipsum
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
